### ISSUE TITLE
node m-build.js throw arguments[0];

### ISSUE THREAD

**Issue by mosci** [mway-io/Espresso#2]
i'm at least able to start & build the KitchenSink-Example
but
when trying to follw the steps on 
http://www.the-m-project.org/getStarted_helloworld.html

i can not start nor build the app:
node m-build.js 

Building application: "next"
Building components:
calling build() for: "test_App"
calling build() for: "test_AppResources"
calling build() for: "core"
calling build() for: "ui"
calling build() for: "jquery"
calling build() for: "underscore"
calling build() for: "themes"
calling build() for: "bootstrapping"
calling build() for: "jquery_mobile_plugins"
calling build() for: "jquery_mobile"

<...>/Espresso/lib/step.js:36
        throw arguments[0];
                       ^
SyntaxError: Unexpected token :
    at Object.parse (native)
    at <...>/Espresso/core/framework.js:149:27
    at [object Object].<anonymous> (fs.js:86:5)
    at [object Object].emit (events.js:39:17)
    at afterRead (fs.js:843:12)

**Comment by mway-io** [comment]
Hey mosci, it's a bug in the manifest.json, that we will fix as soon as possible. You can fix it in your Hello World app by simply editing the manifest.json in the jQM folder:

Open the manifest.json file in 'frameworks=>The-M-Project=>modules=>jquery_mobile" and add curly brackets around the code, so that it looks like the following:

{ 
"manifest": ["...", "...", "..."]
}

This fixes your issue. As I said, it will be fixed in Espresso, too.

**Comment by mosci** [comment]
thanks for the workarround - works fine!

**Comment by dominiklaubach** [comment]
I reopened this issue since this still needs to be fixed in Espresso. We will close it once it's done.
