### ISSUE TITLE
symlink to latest build folder

### ISSUE THREAD

**Issue by hano** [mway-io/Espresso#28]
ssia

**Comment by dominiklaubach** [comment]
Maybe we should re-organize the way builds are stored on the HDD. What do you think about something like 'espresso build -p 'path/to/my/build'. Otherwise we could use the deploy command for this stuff, e.g.: 'espresso deploy localConfig'. 

'localConfig' would be defined in config.json and tell Espresso where to store the build.

**Comment by dominiklaubach** [comment]
Done with commit 8fa334459d70904340c5d826e501a1c0eda563e8. Check the Esspresso wiki for futher information: https://github.com/mwaylabs/Espresso/wiki/Config.json
