### ISSUE TITLE
Core.js from The M Project core framework is compiled out of order

### ISSUE THREAD

**Issue by greylurk** [mway-io/Espresso#53]
The file generated from Espresso both when using "espresso server" and "espresso build" on a fresh copy of the KitchenSink app from the M Framework sample code gets a core.js which is concatenated out of order.  Because of this, the "core/foundation/models.js" is included before "core/foundation/m.js" which results in the namespace not being defined when trying to execute the application.

**Comment by greylurk** [comment]
See the core.js file generated at https://gist.github.com/1631800

**Comment by dominiklaubach** [comment]
Hi greylurk,

first of all, thank you very much for posting this issue! But actually this is a bug within The-M-Project, since we messed up with our internally used "m_require" stuff which tells Espresso how to concatenate the files on build/server.

Anyway, it should be fixed now. I'd appreciate it if you could test it again. Thank you very much in advance.

Best regards
Dominik

**Comment by greylurk** [comment]
Confirmed fixed.  Thank you for your quick attention to this.

**Comment by dominiklaubach** [comment]
Allright, thank you again for reporting this important thing!
